/* tslint:disable */
/* eslint-disable */
/**
 * Treuhand CRM API
 * OAuth Login
 *
 * The version of the OpenAPI document: 1.0
 * Contact: develop@upcraft.li
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

